/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.9 shoe.gltf 
*/

import React, {useRef} from "react";
import {useGLTF} from "@react-three/drei";

export default function Model(props) {
  const {nodes, materials} = useGLTF("/shoe.gltf");
  return (
    <group {...props} dispose={null} scale={3}>
      <mesh
        geometry={nodes.shoe.geometry}
        material={materials.laces}
        material-color={props.colors.main}
      />
      <mesh
        geometry={nodes.shoe_1.geometry}
        material={materials.mesh}
        material-color={props.colors.seccolor}
      />
      <mesh geometry={nodes.shoe_2.geometry} material={materials.caps} />
      <mesh
        geometry={nodes.shoe_3.geometry}
        material={materials.inner}
        material-color={props.colors.maincolor}
      />
      <mesh geometry={nodes.shoe_4.geometry} material={materials.sole} />
      <mesh
        geometry={nodes.shoe_5.geometry}
        material={materials.stripes}
        material-color={props.colors.thridcolor}
      />
      <mesh
        geometry={nodes.shoe_6.geometry}
        material={materials.band}
        material-color={props.colors.thridcolor}
      />
      <mesh
        geometry={nodes.shoe_7.geometry}
        material={materials.patch}
        material-color={props.colors.thridcolor}
      />
    </group>
  );
}

useGLTF.preload("/shoe.gltf");
